# branch-defaults:
#   master:
#     environment: oldCollab-prod-env
# environment-defaults:
#   oldCollab-prod-env:
#     branch: null
#     repository: null
# global:
#   application_name: old-collaborateV1
#   default_ec2_keyname: null
#   default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
#   default_region: eu-north-1
#   include_git_submodules: true
#   instance_profile: null
#   platform_name: null
#   platform_version: null
#   profile: null
#   sc: git
#   workspace_type: Application
